name: Publish Package
on:
  workflow_dispatch: # Manually triggered workflow
    inputs:
      tag_name:
        description: 'Tag for the release (e.g., 2.0.0)'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build --configuration Release --no-restore
    - name: Run Tests
      run: dotnet test
    - name: Pack NuGet Package
      run: dotnet pack --configuration Release --output ./artifacts
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./artifacts/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
    - name: Create GitHub Release
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.tag_name }}
        release_name: v${{ github.event.inputs.tag_name }}
        body: |
          This release includes the latest changes and updates. Review the CHANGELOG for details.
        draft: false
        prerelease: false

